---
# tasks file for docker
#
- name: install docker repo
  yum_repository:
    gpgkey: "https://download.docker.com/linux/centos/gpg"
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    name: "Docker CE Stable"

- name: install docker packages
  yum:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: present

- name: enable and start docker service
  service:
    name: docker
    state: started
    enabled: true